name: W-Assistant-WhatsApp-Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # Runs every 5 hours to keep the bot alive

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start W-Assistant AI Bot
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        run: npm start
