name: W-Assistant-WhatsApp-Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # Runs every 5 hours to keep the bot alive

jobs:
  build:
    runs-on: ubuntu-latest
    
    # گٹ ہب کو زیادہ دیر چلنے دینے کے لیے ٹائم آؤٹ سیٹ کیا گیا ہے
    timeout-minutes: 360 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start W-Assistant AI Bot
        env:
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
          # ElevenLabs کے لیے نئی لائنز ایڈ کی گئی ہیں
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
        run: npm start
